export const productActionType = {
    ALL_PRODUCT_REQUEST : "ALL_PRODUCT_REQUEST",
    ALL_PRODUCT_SUCCESS : "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_FAIL : "ALL_PRODUCT_FAIL",

    PRODUCT_DETAILS_REQUEST : "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS : "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL : "PRODUCT_DETAILS_FAIL",

    ADMIN_PRODUCT_REQUEST : "ADMIN_PRODUCT_REQUEST",
    ADMIN_PRODUCT_SUCCESS : "ADMIN_PRODUCT_SUCCESS",
    ADMIN_PRODUCT_FAIL : "ADMIN_PRODUCT_FAIL",

    NEW_PRODUCT_REQUEST : "NEW_PRODUCT_REQUEST",
    NEW_PRODUCT_SUCCESS : "NEW_PRODUCT_SUCCESS",
    NEW_PRODUCT_FAIL : "NEW_PRODUCT_FAIL",

    DELETE_PRODUCT_REQUEST : "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SUCCESS : "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL : "DELETE_PRODUCT_FAIL",

    UPDATE_PRODUCT_REQUEST : "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS : "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAIL : "UPDATE_PRODUCT_FAIL",
    UPDATE_PRODUCT_RESET : "UPDATE_PRODUCT_RESET",

    CLEAR_ERRORS : "CLEAR_ERRORS"
}